---
title: "Lectures"
---

The course covers the following main topics, with corresponding lecture
materials available in the [lectures folder in our course repository](https://github.com/danilofreire/qtm151-summer/tree/main/lectures):

## Schedule

- Tuesday, May 13: [Lecture 01: Welcome to QTM 151 - Introduction and Course Overview](https://raw.githack.com/danilofreire/qtm151-summer/main/lectures/lecture-01/01-introduction.html).
  Please make sure to install the necessary software for the course by following the [Course Tutorials: How to Install Anaconda, Jupyter, PostgreSQL, VSCode, and Open a Free Educational Account on GitHub](https://danilofreire.github.io/qtm151/tutorials/tutorials.html).

- Wednesday, May 14: Lecture 02: Jupyter Notebooks, Packages, Variables, and Lists. [Lecture Slides](https://raw.githack.com/danilofreire/qtm151-summer/main/lectures/lecture-02/02-jupyter-variables.html), [Lecture Notebook](https://github.com/danilofreire/qtm151-summer/blob/main/lectures/lecture-02/02-jupyter-variables.ipynb). 

- Thursday, May 15: Lecture 03: Maths Operations, Arrays, and Boolean Logic. [Lecture Slides](https://raw.githack.com/danilofreire/qtm151-summer/main/lectures/lecture-03/03-maths-boolean.html), [Lecture Notebook](https://github.com/danilofreire/qtm151-summer/blob/main/lectures/lecture-03/03-maths-boolean.ipynb)
  - [Kahoot Quiz](https://play.kahoot.it/v2/?quizId=b9d95c73-826e-411a-99c3-1b5cc87780f2&hostId=05eb977d-4f8a-440e-9e45-95212b29d103). The quiz is optional and will not be graded. We will do it in class! It is a fun way to review the material covered in the lecture.

- Friday, May 16: [Lecture 04: Quiz 01 - Based on Lectures 01-03](https://github.com/danilofreire/qtm151-summer-quiz01/). The repository contains the quiz questions and will be made online on the day of the quiz.
  - [Kahoot Quiz](https://play.kahoot.it/v2/?quizId=d8d3593a-52c8-4d6c-b938-d880edb69745&hostId=05eb977d-4f8a-440e-9e45-95212b29d103).

- Monday, May 19: Lecture 05: Conditional Statements. [Lecture Slides](https://raw.githack.com/danilofreire/qtm151-summer/main/lectures/lecture-05/05-conditional-statements.html), [Lecture Notebook](https://github.com/danilofreire/qtm151-summer/blob/main/lectures/lecture-05/05-conditional-statements.ipynb).

- Tuesday, May 20: Lecture 06: While and For Loops. [Lecture Slides](https://raw.githack.com/danilofreire/qtm151-summer/main/lectures/lecture-06/06-loops.html), [Lecture Notebook](https://github.com/danilofreire/qtm151-summer/blob/main/lectures/lecture-06/06-loops.ipynb).

- Wednesday, May 21: Lecture 07: Functions. [Lecture Slides](https://raw.githack.com/danilofreire/qtm151-summer/main/lectures/lecture-07/07-functions.html), [Lecture Notebook](https://github.com/danilofreire/qtm151-summer/blob/main/lectures/lecture-07/07-functions.ipynb).

- Thursday, May 22: Lecture 08: Data Wrangling with Pandas. [Lecture Slides](https://raw.githack.com/danilofreire/qtm151-summer/main/lectures/lecture-08/08-data-wrangling.html), [Lecture Notebook](https://github.com/danilofreire/qtm151-summer/blob/main/lectures/lecture-08/08-data-wrangling.ipynb).

- Friday, May 23: [Lecture 09: Quiz 02 - Based on Lectures 05-08](https://github.com/danilofreire/qtm151-summer-quiz02/). As with Quiz 01, the repository will be available on the day of the quiz.

- Monday, May 26: Lecture 10: Subsetting and Filtering Data. [Lecture Slides](https://raw.githack.com/danilofreire/qtm151-summer/main/lectures/lecture-10/10-subsetting-data.html), [Lecture Notebook](https://github.com/danilofreire/qtm151-summer/blob/main/lectures/lecture-10/10-subsetting-data.ipynb).

- Tuesday, May 27: Lecture 11: Introduction to SQL. [Lecture Slides](https://raw.githack.com/danilofreire/qtm151-summer/main/lectures/lecture-11/11-introduction-sql.html), [Lecture Notebook](https://github.com/danilofreire/qtm151-summer/blob/main/lectures/lecture-11/11-introduction-sql.ipynb).

- Wednesday, May 28: Lecture 12: SQL in Python. [Lecture Slides](https://raw.githack.com/danilofreire/qtm151-summer/main/lectures/lecture-12/12-sql-python.html), [Lecture Notebook](https://github.com/danilofreire/qtm151-summer/blob/main/lectures/lecture-12/12-sql-python.ipynb).

- Thursday, May 29: Lecture 13: Merge Tables in SQL. [Lecture Slides](https://raw.githack.com/danilofreire/qtm151-summer/main/lectures/lecture-13/13-sql-tables.html), [Lecture Notebook](https://github.com/danilofreire/qtm151-summer/blob/main/lectures/lecture-13/13-sql-tables.ipynb).

- Friday, May 30: [Lecture 14: Quiz 03 - Based on Lectures 10-13](https://github.com/danilofreire/qtm151-summer-quiz03/). 

Each lecture folder contains an HTML file or a Jupyter notebook (`.ipynb`) with code examples and explanations, along with any additional resources or datasets used in the lecture.
