---
title: "Tutorials"
---

Below you will find a list of available tutorials with instructions on how to
install and use the tools we will be using in class. 

## Available Tutorials

- [01 - VSCode and Anaconda Tutorial](01-vscode-anaconda-tutorial.qmd)
- [02 - Jupyter Notebook and Markdown Tutorial](02-jupyter-markdown-tutorial.qmd)
- [03 - GitHub Tutorial](03-github-tutorial.qmd)
- [04 - PostgreSQL Tutorial](04-postgresql-tutorial.qmd)

PDF versions of the tutorials are also available on GitHub: <https://github.com/danilofreire/qtm151-summer/tree/gh-pages>.

## Additional Resources

### Further examples

- [testing-ipython.ipynb](testing-ipython.ipynb): A Jupyter Notebook for showing Markdown and code cells
- [testing-anaconda.py](testing-anaconda.py): A Python script for testing Anaconda installation

### Suggested Books

- [Python for Data Analysis](https://wesmckinney.com/book/) by Wes McKinney
- [Elements of Data Science](https://allendowney.github.io/ElementsOfDataScience/README.html) by Allen Downey
- [Automate the Boring Stuff with Python](https://automatetheboringstuff.com) by Al Sweigart
- [Python for Everybody](https://www.py4e.com/book.php) by Charles Severance
- [SQL for Data Scientists](https://sqlfordatascientists.com/) by Renee M. P. Teate

### Online Courses

- [Coursera: Python for Everybody Specialisation](https://www.coursera.org/specializations/python)
- [edX: Python Basics for Data Science](https://www.edx.org/learn/python/ibm-python-basics-for-data-science)
- [Codecademy: Learn Python](https://www.codecademy.com/learn/learn-python-3)
- [DataCamp: Introduction to SQL](https://www.datacamp.com/courses/intro-to-sql-for-data-science)
- [Coursera: SQL for Data Science](https://www.coursera.org/learn/sql-for-data-science)

### Documentation

- [Python Documentation](https://docs.python.org/3/)
- [Pandas Documentation](https://pandas.pydata.org/pandas-docs/stable/)
- [PostgreSQL Documentation](https://www.postgresql.org/docs/)
- [SQLBolt](https://sqlbolt.com/)
- [Github Guides](https://guides.github.com/)


For any questions or issues regarding these tutorials, please [open a GitHub issue](https://github.com/danilofreire/qtm151-summer/issues), [submit a pull request](https://github.com/danilofreire/qtm151-summer/pulls), or [create a discussion post](https://github.com/danilofreire/qtm151-summer/discussions). 

I hope you like the tutorials and find them useful! 
