---
title: "Tutorials"
---

Below you will find a list of available tutorials with instructions on how to
install and use the tools we will be using in class. 

## Available Tutorials

- [01 - VSCode and Anaconda Tutorial](01-vscode-anaconda-tutorial.qmd)
- [02 - Jupyter Notebook and Markdown Tutorial](02-jupyter-markdown-tutorial.qmd)
- [03 - GitHub Tutorial](03-github-tutorial.qmd)
- [04 - PostgreSQL Tutorial](04-postgresql-tutorial.qmd)

PDF versions of the tutorials are also available on GitHub: <https://github.com/danilofreire/qtm151/tree/main/tutorials>.

## Additional Resources

- [python-postgresql-example.ipynb](python-postgresql-example.ipynb): A Jupyter Notebook with a PostgreSQL example
- [testing-ipython.ipynb](testing-ipython.ipynb): A Jupyter Notebook for showing Markdown and code cells
- [testing-anaconda.py](testing-anaconda.py): A Python script for testing Anaconda installation

For any questions or issues regarding these tutorials, please [open a GitHub
issue](https://github.com/danilofreire/qtm151/issues), [submit a pull
request](https://github.com/danilofreire/qtm151/pulls), or [create a discussion
post](https://github.com/danilofreire/qtm151/discussions). I hope you like the
tutorials and find them useful! 
